### ISSUE TITLE
Scheduled deployments

### ISSUE THREAD

**Issue by ohbus** [iluwatar/java-design-patterns-vuepress-web#6]
The deployment is being cancelled because netlify is detecting no content change in [this](https://github.com/iluwatar/java-design-patterns-vuepress-web) repository.

_The content is going to be changed more in the git repositories which it is building for generate the website._

#### There are few things that we need to make sure for this to perform well:
- [ ] Enable **scheduled** build triggers.
- [ ] Deactivate checking content change on [this](https://github.com/iluwatar/java-design-patterns-vuepress-web) repository and continue deployment regardless.

**Comment by iluwatar** [comment]
```
# ./.github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 0 * * *' # Once a day
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/<YOUR_HOOK_ID>
```
